version: "3.3"

services:
  bot:
    build: bot/
    networks:
      - common_network
    environment:
      - BOT_TOKEN=${BOT_TOKEN} 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./../out/logs/bot/:/app/logs/

  database:
    build: database/
    networks:
      - common_network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

networks:
  common_network:
    driver: bridge
